id = "vim-theme"
name = "Vim Theme"
schema_version = 1
version = "0.5.1"
authors = ["Daniel Thompson, Zed Industries and Benjamin Davies"]
description = "A port of the bundled Vim color schemes"
repository = "https://github.com/daniel-thompson/vim-theme-for-zed"
